### ISSUE TITLE
influxdb2client E! parse "192.168.1.5:8086/": first path segment in URL cannot contain colon

### ISSUE THREAD

**Issue by jmoorey1** [OliverCullimore/geo-energy-data#1]
Hi -

I've compiled your code but it's throwing errors when it's trying to write to the database. Quick Google looks like it's a Go error.

`john@batman:/opt/geo-energy-data$ ./geo-energy-data
2021/02/15 11:25:33 Starting geo Energy Data
2021/02/15 11:25:33 Loaded config
2021/02/15 11:25:33 Writing records:
[
  "meterdata,source=live,unit=watts,type=ELECTRICITY val=868.000000 1613388329",
  "meterdata,source=live,unit=watts,type=GAS_ENERGY val=262.000000 1613388329"
]
2021/02/15 11:25:33 Writing records:
[
  "meterdata,source=periodic,unit=watts,type=ELECTRICITY val=2230.966000 1613388233",
  "meterdata,source=periodic,unit=m3,type=GAS_ENERGY val=637671.000000 1613386800",
  "meterdata,source=periodic,unit=watts,type=GAS_ENERGY val=7155.072478 1613386800",
  "meterdata_bill,source=periodic,type=ELECTRICITY,validutc=1613388233,startutc=946684800 val=4080.880000 1613388233",
  "meterdata_bill,source=periodic,type=GAS_ENERGY,validutc=946684800,startutc=1612310400 val=2757.000000 1613388233",
  "meterdata_tariff,source=periodic,type=ELECTRICITY val=12.836000 1613388233",
  "meterdata_tariff,source=periodic,type=GAS_ENERGY val=2.284000 1613388233",
  "meterdata_currentcosts,source=periodic,type=ELECTRICITY,duration=DAY,subtype=cost val=133.317000 1613388233",
  "meterdata_currentcosts,source=periodic,type=ELECTRICITY,duration=DAY,subtype=energy val=9.245000 1613388233",
  "meterdata_currentcosts,source=periodic,type=ELECTRICITY,duration=WEEK,subtype=cost val=133.317000 1613388233",
  "meterdata_currentcosts,source=periodic,type=ELECTRICITY,duration=WEEK,subtype=energy val=9.245000 1613388233",
  "meterdata_currentcosts,source=periodic,type=ELECTRICITY,duration=MONTH,subtype=cost val=4675.798000 1613388233",
  "meterdata_currentcosts,source=periodic,type=ELECTRICITY,duration=MONTH,subtype=energy val=347.098000 1613388233",
  "meterdata_currentcosts,source=periodic,type=GAS_ENERGY,duration=DAY,subtype=cost val=110.000000 1613388233",
  "meterdata_currentcosts,source=periodic,type=GAS_ENERGY,duration=DAY,subtype=energy val=42.031000 1613388233",
  "meterdata_currentcosts,source=periodic,type=GAS_ENERGY,duration=WEEK,subtype=cost val=110.000000 1613388233",
  "meterdata_currentcosts,source=periodic,type=GAS_ENERGY,duration=WEEK,subtype=energy val=42.165000 1613388233",
  "meterdata_currentcosts,source=periodic,type=GAS_ENERGY,duration=MONTH,subtype=cost val=2758.000000 1613388233",
  "meterdata_currentcosts,source=periodic,type=GAS_ENERGY,duration=MONTH,subtype=energy val=1453.437000 1613388233"
2021/02/15 11:25:53 influxdb2client E! parse "192.168.1.5:8086/": first path segment in URL cannot contain colon
2021/02/15 11:25:53 influxdb2client E! Write error: parse "192.168.1.5:8086/": first path segment in URL cannot contain colon
Batch kept for retrying
InfluxDB write error: parse "192.168.1.5:8086/": first path segment in URL cannot contain colon
`

**Comment by jmoorey1** [comment]
Did some more ferreting; needed to add 'http://' to the start of the INFLUXDB_HOST;
`# INFLUX DB
INFLUXDB_HOST=http://192.168.1.5
INFLUXDB_PORT=8086
INFLUXDB_ORG=my-org
INFLUXDB_BUCKET=energy
`

Suspect this line is the issue;
[https://github.com/OliverCullimore/geo-energy-data/blob/18c9a37e27f73df7da81af51f3c2f2a7b8babf36/main.go#L247]

**Comment by OliverCullimore** [comment]
Hi, thank you for bringing this to my attention. I've now added validation to the environment variables and also updated the README file to include more detail on the values expected in each variable.
